---

- name: configure network devices
  hosts: routers
  gather_facts: false
  vars_files: ./group_vars/all.yml
  tasks:
    - name: configure device with config
      cli_config:
        config: "{{ lookup('template', 'router.j2') }}"
