---

- name: Generate configuration files
  hosts: localhost
  gather_facts: no

  tasks:

  - name: Config from template
    template: src=switch-template.j2 dest=./{{ item.hostname }}.txt
    with_items: "{{switches}}"
