---

- name: Generate configuration files
  hosts: localhost
  gather_facts: no

  tasks:

  - name: Config from template
    template: src=vpn-template.j2 dest=./{{ item.name }}_profile.txt
    with_items: "{{vpn}}"
