---

- name: Generate configuration files
  hosts: localhost
  gather_facts: no

  tasks:

  - name: Config from template
    template: src=router.j2 dest=/Users/janblahuta/Documents/GitHub/ansible/Config-Generator/{{ item.hostname }}.txt
    with_items: "{{switches}}"
