---

- name: Cisco show version example
  hosts: routers
  gather_facts: no

  tasks:
   
  - name: configurable backup path
    ios_config:
      save_when: modified
      backup: yes
      backup_options:
        filename: "{{ inventory_hostname }}-{{ansible_date_time.date}}.cfg"
        dir_path: /home/jan/show-output

...



