---

- name: Cisco show version example
  hosts: all
  gather_facts: no

  tasks:
   
  - name: configurable backup path
    cisco.ios.ios_config:
      backup: yes
      backup_options:
        filename: "{{ inventory_hostname }}.cfg"
        dir_path: /home/jan/show-output

...
